### ISSUE TITLE
Null Exception thrown when rebuilding the "sitecore_analytics_index" in Sitecore 7.5

### ISSUE THREAD

**Issue by ctekempel** [aokour/Sitecore.ContentSearch.Spatial#1]
Hi,

While working with this package on a customer build I noticed that the experience profile was not updating as users sessions expired. After digging into it a bit I realized that it was to do with the Sitecore analytics  index(which drives a lot of the experience profile) not updating. Looking into the crawling logs there is a null exception being thrown from within the "LuceneSpatialDocumentBuilder.AddItemFields" method.

To resolve this, we removed patched out the "LuceneSpatialDocumentBuilder" class from the default lucene index configuration and only added it to a specific spatial index configuration.

In terms of possible fixes, I can see two parts:
1. Create a new index configuration based on the default configuration(using the ref aspect of the sitecore config system) that way the analytics index is unaffected
2. add a check to prevent the null exception form being thrown

Happy to jump in and help out, just point me in the direction you would like to see it go.

**Comment by aokour** [comment]
Thanks! I will create new index configuration to be used only with master/web indexes, also will add null check to Document builder.
Thanks again to point out this issue!

**Comment by ctekempel** [comment]
No worries. Happy to help =)
