### ISSUE TITLE
Results being cached

### ISSUE THREAD

**Issue by mikeedwards83** [aokour/Sitecore.ContentSearch.Spatial#3]
I am having a problem where the search results don't update when I add an item or change a value.

The results do show after an IIS reset. Have you seen this problem before? I am using Sitecore 8.1.

**Comment by aokour** [comment]
Hey Mike,
I did notice this issue recently, and i'm trying to figure out whats the issue, Sitecore seems to cache the index at some point and i need to refresh that cache once the lat/lng fields is saved.
I saw that doing full index fixes the issue, but that's not ideal solution, so i will keep digging around.

**Comment by ghost** [comment]
I am currently having the same issue.  We are on 8.2 update 2 and every time we re-index manually the same search comes back with different results.  If we then recycle the app pool in IIS then it comes back with all the appropriate results.  There is definitely something odd going on with Sitecore Caching.

Any updates on this?

**Comment by aokour** [comment]
This has been fixed in latest commits
