### ISSUE TITLE
CreateSearcherOption could not be found in

### ISSUE THREAD

**Issue by huzzi** [aokour/Sitecore.ContentSearch.Spatial#4]
I'm getting the type or namespace **CreateSearcherOption** could not be found in
In Sitecore.ContentSearch.Spatial/Source/Sitecore.ContentSearch.Spatial/Provider/Lucene/LuceneSearchWithSpatialContext.cs. 

`protected LuceneSearchWithSpatialContext(ILuceneProviderIndex index, CreateSearcherOption options = CreateSearcherOption.Writeable, SearchSecurityOptions securityOptions = SearchSecurityOptions.EnableSecurityCheck) : base(index, options, securityOptions)
        {
            Assert.ArgumentNotNull(index, "index");
            this.index = index;
            this.settings = this.index.Locator.GetInstance<IContentSearchConfigurationSettings>();
        }`

If I comment out the bit of code and run, I get "Current Index is not configured to use Spatial Search."

Using Sitecore V8.1, I've included all the required dlls.

Please help. Many thanks.

**Comment by huzzi** [comment]
The overridden method CreateSearchContext is not getting called.

**Comment by SitecoreSandbox** [comment]
I have this exact same problem. @huzzi did you ever get this resolved and get this working in 8.1?

**Comment by SitecoreSandbox** [comment]
I determined this was due to the wrong index being created for search context. It needs to be set to the actual index that was being used. In the examples, I used "sitecore_master_index" but my code was calling another index that was not setup for spatial search:

`using (var searchContext = ContentSearchManager.GetIndex("[SET TO INDEX YOU SETUP IN CONFIG]").CreateSearchContext())
                        {
                            results.AddRange(searchContext.GetExtendedQueryable<SpatialSearchResultItem>()
                                .Where(item => item.GeoLocation.WithinRadius(location.Latitude, location.Longitude, radius)).ToList());
                        }`

**Comment by aokour** [comment]
@SitecoreSandbox So its working for you now?

**Comment by aokour** [comment]
@huzzi Were you able to fix the issue using the correct Index name?

**Comment by SitecoreSandbox** [comment]
Yes, I got past that issue, once I got the correct index name in place and setup the index to use the correct assembly. I know this as I was able to debug through the code to see that I am getting the index back. I am good now.

**Comment by huzzi** [comment]
Almost there, I can run the project on it's own but when i try to integrate the code within an existing problem I'm getting the error message below:

`Could not create instance of type: Abc.Spatial.Provider.Lucene.LuceneIndexWithSpatial. No matching constructor was found.`

Thrown by Indexing Manager.

Any idea?

@aokour @SitecoreSandbox

**Comment by huzzi** [comment]
All sorted now
